-- Generated by nwg-displays on 2026-06-03 at 15:00:54. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "3456x2160@60.0",
    position = "0x360",
    scale = 2.0
})
hl.monitor({
    output = "DP-4",
    mode = "3840x2160@120.0",
    position = "1728x0",
    scale = 1.5
})
